// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistracijaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:8080"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registracija() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.cssSelector("a:nth-child(2) > img")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".offset-sm-2 > .row > .col-sm-2 > a:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("imeiprezime")).click();
    driver.findElement(By.name("imeiprezime")).sendKeys("jovana jelcic");
    driver.findElement(By.name("korime")).click();
    driver.findElement(By.name("korime")).sendKeys("jelciceva");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("jovanajelcic@gmail.com");
    driver.findElement(By.name("lozinka")).click();
    driver.findElement(By.name("lozinka")).sendKeys("kkkkkkkkkk");
    driver.findElement(By.name("ponloz")).click();
    driver.findElement(By.name("ponloz")).sendKeys("kkkkkkkkkk");
    driver.findElement(By.name("adresa")).click();
    driver.findElement(By.name("adresa")).sendKeys("milosa savkovica 21");
    driver.findElement(By.name("telefon")).click();
    driver.findElement(By.name("telefon")).sendKeys("0691226066");
    driver.findElement(By.cssSelector("td:nth-child(1) > input")).click();
    driver.findElement(By.cssSelector("table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2)")).click();
    driver.findElement(By.cssSelector("table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2) > font")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2) > font")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2) > font"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2) > font")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2) > font")).getText(), is("Postoji korisnik sa ovim korisničkim imenom"));
    driver.findElement(By.name("korime")).click();
    driver.findElement(By.name("korime")).sendKeys("jelciceva123");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("jovanajjelcic@gmail.com");
    driver.findElement(By.name("lozinka")).click();
    driver.findElement(By.name("lozinka")).sendKeys("123123123");
    driver.findElement(By.name("ponloz")).click();
    driver.findElement(By.name("ponloz")).sendKeys("123123123");
    driver.findElement(By.cssSelector("td:nth-child(1) > input")).click();
  }
}
